"""Investigation result container model.

Aggregates all findings from a complete investigation run with execution
metadata. This is the top-level output of the Investigation Engine.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, computed_field

from investigation_engine.models.dataset import DatasetInfo
from investigation_engine.models.finding import Finding
from investigation_engine.models.severity import Severity
from investigation_engine.models.investigation_hypothesis import Investigation
from investigation_engine.reasoning.evidence.models import EvidenceUnit
from investigation_engine.reasoning.hypothesis.models import Hypothesis
from investigation_engine.reasoning.knowledge.models import KnowledgeObject


class ModuleExecutionRecord(BaseModel):
    """Execution metadata for a single module run.

    Tracks timing, finding counts, and error information for each
    module executed during an investigation.
    """

    module_name: str = Field(..., description="Name of the executed module.")
    status: str = Field(
        ...,
        description="Execution status: 'success', 'failed', or 'skipped'.",
    )
    finding_count: int = Field(default=0, ge=0, description="Number of findings produced.")
    duration_seconds: float = Field(default=0.0, ge=0.0, description="Execution time in seconds.")
    error_message: str | None = Field(
        default=None,
        description="Error message if the module failed.",
    )
    skipped_reason: str | None = Field(
        default=None,
        description="Reason the module was skipped (from can_run).",
    )


class InvestigationResult(BaseModel):
    """Complete result of an investigation run.

    This is the top-level output of the Investigation Engine, containing
    all findings from all modules, dataset metadata, and execution records.

    Attributes:
        id: Unique identifier for this investigation run.
        dataset_info: Metadata about the investigated dataset.
        findings: All findings from all modules, ordered by severity.
        module_records: Execution records for each module.
        modules_executed: Names of successfully executed modules.
        modules_failed: Names of modules that failed.
        modules_skipped: Names of modules that were skipped.
        started_at: Investigation start time (UTC).
        completed_at: Investigation completion time (UTC).
        duration_seconds: Total investigation duration.
        metadata: Extensible metadata for the investigation run.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique investigation run identifier.",
    )
    dataset_info: DatasetInfo = Field(
        ...,
        description="Metadata about the investigated dataset.",
    )
    findings: list[Finding] = Field(
        default_factory=list,
        description="All findings from all modules.",
    )
    evidence_units: list[EvidenceUnit] = Field(
        default_factory=list,
        description="Compressed evidence units synthesized from raw findings.",
    )
    knowledge_objects: list[KnowledgeObject] = Field(
        default_factory=list,
        description="Reusable semantic concepts constructed from evidence units.",
    )
    hypotheses: list[Hypothesis] = Field(
        default_factory=list,
        description="Evidence-backed hypotheses generated from knowledge objects.",
    )
    investigations: list[Investigation] = Field(
        default_factory=list,
        description="Prioritized investigation queue generated by the reasoning pipeline.",
    )
    module_records: list[ModuleExecutionRecord] = Field(
        default_factory=list,
        description="Execution records for each module.",
    )
    modules_executed: list[str] = Field(
        default_factory=list,
        description="Names of successfully executed modules.",
    )
    modules_failed: list[str] = Field(
        default_factory=list,
        description="Names of modules that failed during execution.",
    )
    modules_skipped: list[str] = Field(
        default_factory=list,
        description="Names of modules that were skipped (can_run returned False).",
    )
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Investigation start time (UTC).",
    )
    completed_at: datetime | None = Field(
        default=None,
        description="Investigation completion time (UTC).",
    )
    duration_seconds: float = Field(
        default=0.0,
        ge=0.0,
        description="Total investigation duration in seconds.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extensible investigation run metadata.",
    )
    reasoning_metrics: dict[str, Any] | None = Field(
        default=None,
        description="Optional explainable reasoning metrics for the run.",
    )
    provenance_trees: list[dict[str, Any]] | None = Field(
        default=None,
        description="Optional rendered reasoning lineage trees.",
    )
    benchmark_reports: dict[str, Any] | None = Field(
        default=None,
        description="Optional benchmark results attached to the run.",
    )

    model_config = {
        "frozen": False,
        "json_schema_extra": {
            "title": "InvestigationResult",
            "description": "Complete output of an Investigation Engine run.",
        },
    }

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_findings(self) -> int:
        """Total number of findings across all modules."""
        return len(self.findings)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def critical_findings(self) -> int:
        """Count of critical severity findings."""
        return sum(1 for f in self.findings if f.severity == Severity.CRITICAL)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def high_findings(self) -> int:
        """Count of high severity findings."""
        return sum(1 for f in self.findings if f.severity == Severity.HIGH)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def actionable_findings(self) -> int:
        """Count of findings requiring analyst action (CRITICAL, HIGH, MEDIUM)."""
        return sum(1 for f in self.findings if f.is_actionable)

    def findings_by_severity(self, severity: Severity) -> list[Finding]:
        """Filter findings by severity level.

        Args:
            severity: The severity level to filter by.

        Returns:
            List of findings matching the specified severity.
        """
        return [f for f in self.findings if f.severity == severity]

    def findings_by_module(self, module_name: str) -> list[Finding]:
        """Filter findings by source module.

        Args:
            module_name: Name of the module to filter by.

        Returns:
            List of findings from the specified module.
        """
        return [f for f in self.findings if f.module == module_name]

    def findings_for_column(self, column_name: str) -> list[Finding]:
        """Get all findings affecting a specific column.

        Args:
            column_name: The column name to search for.

        Returns:
            List of findings that affect the specified column.
        """
        return [f for f in self.findings if column_name in f.affected_columns]

    def get_severity_summary(self) -> dict[str, int]:
        """Get a count of findings by severity level.

        Returns:
            Dictionary mapping severity names to finding counts.
        """
        return {
            severity.value: sum(1 for f in self.findings if f.severity == severity)
            for severity in Severity
        }

    def sort_findings_by_severity(self) -> None:
        """Sort findings in-place by severity (CRITICAL first) then confidence."""
        self.findings.sort(
            key=lambda f: (
                list(Severity).index(f.severity),
                -f.confidence,
            )
        )
